---
- hosts: server
  become: yes

  tasks:
    - name: Install essential commands on Ubuntu
      apt:
        name: ['ranger', 'net-tools', 'tree', 'ncdu', 'neofetch', 'vim', 'mosh', 'tmux', 'htop', 'git', 'curl', 'wget', 'unzip', 'zip', 'gcc', 'build-essential', 'make']
        state: present
      become: yes
    