- name: Configure Nginx
- hosts: server
  become: yes
  vars:
    - user_name: "Hello"

  tasks:
  - name: Prints two lines of messages, but only if there is an environment value set
    ansible.builtin.debug:
    msg:
    - "Hello Mr{{ user_name }}"
