---
- hosts: server
  become: yes
  vars:
    - user_name: "Hello"
    - love: "False"

  tasks:
    - debug:
        msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }} and say {{ user_name }}"

    - name: Debug
      debug:
        msg: "Changed with love! Love state: {{ love }}"
