- hosts: server
  become: yes
  var_files:
    - values.yaml

  tasks:
  - name: Generate sshkey for {{ user }} 
    user:
      name: "{{ user }}" 
      generate_ssh_key: yes
      ssh_key_type: rsa
      ssh_key_bits: 2048
      ssh_key_file: ".ssh/{{ ansible_hostname }}"
      force: no
      become: yes

  - name: Copy ssh-key to authorized_keys
    copy:
      src: "~/.ssh/{{ ansible_hostname }}.pub"
      dest: "~/.ssh/authorized_keys"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0664
      remote_src: yes
      become: yes
      become_user: "{{ user }}"
            
  - name: Get .pem file from remote server
    fetch:
      src: "~/.ssh/{{ ansible_hostname }}"
      dest: "{{ pemfile_path }}/{{ ansible_hostname}}.pem"
      mode: 0400
      flat: yes
      become: yes
      become_user: "{{ user }}"

  - name: Configure SSH
    template:
      src: "./templates/sshd_config.j2"
      dest: "/etc/ssh/sshd_config"
